---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3837303635-gtvPxtSczcZ0IA3voevYS8eVXR6JzwNrM8xlXcW
:access_token_secret: TfBvNEcjkLrEJmXtkI0BXZJrOZn5pKSerqWQuCp3enraS
