# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c2af273aa733e3529f143de19a621f67373d8d99d27e676fec53fa2f818e2d8ddefe349249ac34f0be6c39c7f1dbca0bf714e5586c2cd02d72e213a53e213d6

test:
  secret_key_base: 309a782ca78e1e788fa342fedcff9a898f6e252b6313978134e1bf3c95bbec34ad9748ba05963ffd53d703f46d71ff0d5ea862073f351d97c143781e2a6c321e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
